# These are supported funding model platforms

github: [csa7mdm]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: buymeacoffee.com/csa7mdmc
thanks_dev:
custom: ['https://www.buymeacoffee.com/ahmedmustafa']
